In [52]:
import numpy as np
import pandas as pd

df = pd.read_csv('student-mat.csv')
df['grade_mean'] = (df['G1'] + df['G2'] + df['G3']) / 3

# Analysis of Final Scores Mean
print(df["grade_mean"].describe())

# Filtering scores on based Sex
gender_stats = df.groupby('sex')['grade_mean'].agg(['mean', 'std', 'count'])
print(gender_stats)
print('='*60) 

# Analyse of Factors Affecting Student Grades
abcence_mean = df.groupby('absences')['grade_mean'].agg([ 'count', 'mean', 'std'])
print(abcence_mean)
print("correlation between absence numbers and student's mean of scores : ", 
      np.corrcoef(df["absences"], df['grade_mean'])[0, 1])                               # Effect of Number of Abcences
print('='*60) 

df['parents_edu'] = (df['Medu'] + df['Fedu']) / 2
parents_edu = df.groupby(["parents_edu"])['grade_mean'].agg([ 'count', 'mean', 'std'])
print(parents_edu)
print("correlation between parents education and student's mean of scores : ", 
      np.corrcoef(df["parents_edu"], df['grade_mean'])[0, 1])                             # Effect of Parents Education
print('='*60) 

school_sort = df.groupby(["school"])['grade_mean'].agg([ 'count', 'mean', 'std'])         # Effect of type of school
print(school_sort)                                                               
print('='*60)

mother_job = df.groupby(["Mjob"])['grade_mean'].agg([ 'count', 'mean', 'std'])           # Effect of Motehr's Job
print(mother_job)
print('='*60)

father_job = df.groupby(["Fjob"])['grade_mean'].agg([ 'count', 'mean', 'std'])           # Effect of Father's Job
print(father_job)
print('='*60) 

parents_job = df.groupby(["Fjob", 'Mjob'])['grade_mean'].agg([ 'count', 'mean', 'std'])  # Effect of Parents Job
print(parents_job)
print(parents_job['mean'].agg(['argmax', 'max', 'argmin', 'min'])) 
print('='*60)

triple_group = df.groupby(['sex', 'age'])['grade_mean'].agg(['mean', 'count'])          # group mean of scores by sex and age
print(triple_group.groupby('sex')['mean'].max())

count    395.000000
mean      10.679325
std        3.696786
min        1.333333
25%        8.333333
50%       10.666667
75%       13.333333
max       19.333333
Name: grade_mean, dtype: float64
          mean       std  count
sex
F    10.325321  3.614018    208
M    11.073084  3.757272    187
============================================================
          count       mean       std
absences
0           115   9.626087  4.710767
1             3  12.666667  0.881917
2            65  11.779487  2.851216
3             8  11.500000  2.845213
4            53  11.075472  2.991899
5             5  11.266667  5.371737
6            31  11.344086  3.361529
7             7  11.523810  3.980774
8            22  10.636364  2.943757
9             3  13.111111  3.338884
10           17  11.058824  3.127466
11            3  11.888889  3.203008
12           12  10.777778  2.775555
13            3  12.000000  5.174725
14           12   9.611111  2.967274
15            3   8.111111  1.018350
16            7  10.000000  3.338884
17            1  10.000000       NaN
18            5   8.800000  2.734553
19            1  10.000000       NaN
20            4  11.833333  2.645751
21            1  17.666667       NaN
22            3   8.555556  3.024591
23            1  13.000000       NaN
24            1  18.000000       NaN
25            1   9.333333       NaN
26            1   6.333333       NaN
28            1   9.333333       NaN
30            1   8.000000       NaN
38            1   8.333333       NaN
40            1  11.666667       NaN
54            1  11.333333       NaN
56            1   8.666667       NaN
75            1   9.333333       NaN
correlation between absence numbers and student's mean of scores :  -0.005908806132303001
============================================================
             count       mean       std
parents_edu
0.5              2  11.333333  4.714045
1.0             39   9.076923  3.398883
1.5             43   9.689922  3.867101
2.0             72  10.162037  3.287475
2.5             47  10.617021  3.672577
3.0             64  11.203125  3.454730
3.5             58  11.247126  4.160784
4.0             70  11.785714  3.579795
correlation between parents education and student's mean of scores :  0.22212797032378032
============================================================
        count       mean       std
school
GP        349  10.737345  3.717529
MS         46  10.239130  3.543496
============================================================
          count       mean       std
Mjob
at_home      59   9.762712  3.627297
health       34  12.235294  3.270652
other       141  10.059102  3.527732
services    103  11.207120  3.906343
teacher      58  11.270115  3.589815
============================================================
          count       mean       std
Fjob
at_home      20  10.816667  4.390946
health       18  11.481481  2.986292
other       217  10.390169  3.661099
services    111  10.669670  3.390270
teacher      29  12.287356  4.636573
============================================================
                   count       mean       std
Fjob     Mjob
at_home  at_home       7  13.190476  4.206948
         other         5   9.466667  1.386442
         services      6   9.111111  5.088840
         teacher       2  11.000000  7.542472
health   at_home       2  11.833333  2.592725
         health        6  13.222222  3.215702
         other         2  11.833333  1.649916
         services      4  10.000000  2.708013
         teacher       4  10.000000  3.277307
other    at_home      33   9.232323  3.237674
         health       17  11.784314  2.676910
         other       104   9.996795  3.706752
         services     42  11.515873  3.997426
         teacher      21  10.777778  3.353826
services at_home      15   9.777778  3.296623
         health       10  12.566667  4.394300
         other        24   9.986111  3.277031
         services     43  10.868217  3.315938
         teacher      19  10.789474  3.059514
teacher  at_home       2   4.333333  1.885618
         health        1  10.666667       NaN
         other         6  11.333333  3.204164
         services      8  13.583333  5.368190
         teacher      12  13.361111  4.083617
argmax    22.000000
max       13.583333
argmin    19.000000
min        4.333333
Name: mean, dtype: float64
============================================================
sex
F    14.666667
M    13.333333
Name: mean, dtype: float64